security:
    encoders:
        App\Entity\User: argon2i

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            host: '%admin_host_pattern%'
            anonymous: ~
            logout:
                path: admin_logout
                delete_cookies:
                    PHPSESSID: ~
            form_login:
                provider: user_provider
                csrf_token_generator: security.csrf.token_manager
                check_path: admin_login_check
                login_path: admin_login

        www:
            anonymous: ~
            logout:
                path: www_logout
            form_login:
                provider: user_provider
                csrf_token_generator: security.csrf.token_manager
                check_path: www_login_check
                login_path: www_login

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { host: '%admin_host_pattern%', roles: ROLE_EMPLOYEE }

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_ADMIN

        ROLE_ADMIN:
            - ROLE_EMPLOYEE
