# Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
# See the official DoctrineExtensions documentation for more details: https://github.com/Atlantic18/DoctrineExtensions/tree/master/doc/
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree:           false
            timestampable:  false
            blameable:      true
            sluggable:      false
            translatable:   false
            loggable:       false
            softdeleteable: false
            uploadable:     false
            sortable:       false
