version: '3.7'

services:
    app:
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            OPCACHE: 'false'
            MIGRATIONS: 'false'
        volumes:
            - ./docker/php/php-dev.ini:/usr/local/etc/php/php.ini
