version: '3.7'

services:
    app:
        image: automagistre/app:dev
        hostname: automagistre.local
        labels:
            subdomains: sto www
            restartable: 'true'
        volumes:
            - ../:/usr/local/app
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            XDEBUG: 'false'
            OPCACHE: 'true'
            MIGRATIONS: 'false'

    mysql:
        image: mariadb:10.3.10
        hostname: mysql.automagistre.local
        volumes:
            -
                type: tmpfs
                target: /var/lib/mysql
                tmpfs:
                    size: 1024m
            - ../:/usr/local/app
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: db
            MYSQL_PASSWORD: db
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        healthcheck:
            test: CMD echo "SELECT 1" | mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 10s

    memcached:
        image: memcached:1.5.11-alpine
        labels:
            restartable: 'false'
        healthcheck:
            test: nc -z 127.0.0.1 11211
            interval: 5s
            timeout: 5s
            retries: 3
            start_period: 5s
