easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    condition: request.getHost() matches '/sto.automagistre.(ru|local)/'

app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
