_admin:
    resource: './routes/admin.yaml'
    condition: "request.getHost() matches '/%admin_host_pattern%/'"
    name_prefix: admin_

# MUST BE LAST
_easy_admin:
    resource: '@EasyAdminBundle/Controller/AdminController.php'
    type: annotation
    condition: "request.getHost() matches '/%admin_host_pattern%/'"
    prefix: /{tenant}

_www:
    resource: './routes/www.yaml'
    condition: "request.getHost() matches '/%www_host_pattern%/'"
    name_prefix: www_
