parameters:
    locale: ru
    env(APP_VERSION): null
    admin_host_pattern: '^(sto|sto\.rc).automagistre.(ru|local)$'
    www_host_pattern: '^(www|www\.rc).automagistre.(ru|local)$'

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true
        bind:
            $debug: '%kernel.debug%'

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags:
                - { name: doctrine.event_subscriber }

        Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface:
            tags:
                - { name: controller.argument_value_resolver, priority: 50 }

    App\:
        resource: '../src'
        exclude: '../src/{Entity,Model}'
    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags:
            - { name: controller.service_arguments }

    App\Partner\Ixora\Finder:
        arguments:
            - '@csa_guzzle.client.ixora_ws'

    App\Partner\Ixora\Orders:
        arguments:
            - '@csa_guzzle.client.ixora_ws'
            - '@serializer'

    Symfony\Bridge\Doctrine\Form\DoctrineOrmTypeGuesser:
        alias: easyadmin.form.guesser.missing_doctrine_orm_type_guesser

    App\Router\BrandRouter:
        decorates: router
        arguments:
            $router: '@App\Router\BrandRouter.inner'
