parameters:
    locale: ru

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true
        bind:
            $debug: '%kernel.debug%'
            string $telegramBotToken: '%env(TELEGRAM_BOT_TOKEN)%'

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags:
                - { name: doctrine.event_subscriber }

        Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface:
            tags:
                - { name: controller.argument_value_resolver, priority: 50 }

        App\Shared\Identifier\IdentifierFormatterInterface:
            tags:
                - { name: identifier_formatter }

    App\:
        resource: '../src'
        exclude: '../src/*/config.php'

    Symfony\Bridge\Doctrine\Form\DoctrineOrmTypeGuesser:
        alias: easyadmin.form.guesser.missing_doctrine_orm_type_guesser

    App\Tenant\Tenant:
        factory: ['App\Tenant\Tenant', 'fromEnv']
