easy_admin:
    entities:
        Note:
            class: App\Note\Entity\Note
            controller: App\Note\Controller\NoteController
            disabled_actions: ['show', 'list', 'search', 'autocomplete', 'edit']
